### ISSUE TITLE
we're seeing test timeout failures with the latest dart dev sdk on travis

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart-pad#1002]
https://travis-ci.org/dart-lang/dart-services/builds/518448624

This likely started happening with 2.2.1-dev.4.0.

**Comment by RedBrogdon** [comment]
Looks like this has been resolved. 

https://travis-ci.org/dart-lang/dart-services/pull_requests

**Comment by devoncarew** [comment]
I think this is still an issue.

**Comment by domesticmouse** [comment]
This is still an issue. https://travis-ci.org/dart-lang/dart-services/jobs/597938851
